### ISSUE TITLE
XDL on Firefox

### ISSUE THREAD

**Issue by b4lanceed** [NightStrang6r/XDL#1]
A lot of guys using Firefox too, please add XDL to Firefox. NURE students will be grateful to you.

**Comment by NightStrang6r** [comment]
Hello. Yes, this is true, indeed many people use Firefox and initially the extension should have been released to all popular browsers, including Firefox. But there is a reason for this.

Apart from the fact that firefox uses a slightly different API for extensions than chromium browsers, it also does not support MANIFEST V3 (https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/) . While the Chrome Web Store around the beginning of this year does not accept extensions developed under MANIFEST V2 and below (https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/).

The current version of XDL uses manifest v3. The latest version of the extension that worked on manifest v2 is XDL v1.0.2. These versions are very different from each other. That is why, unfortunately, we do not have the technical ability to support both options. It remains only to wait for manifest v3 to become available in Firefox.
